### ISSUE TITLE
为什么不在gf项目里做个命令一键生成空项目？

### ISSUE THREAD

**Issue by arden** [gogf/gf-empty#1]
为什么不在gf项目里做个命令一键生成空项目？这样多方便，类似beego通过命令行维护。

**Comment by johngcn** [comment]
@arden 不好意思刚看到你的消息，有打算做个类似beego那样的工具。

**Comment by johngcn** [comment]
@arden 参考`gf-cli`工具 https://goframe.org/toolchain/cli
